const tasks = [
    {
      id: 1,
      title: "Buy Groceries",
      description: "Purchase milk, eggs.",
      date: "2023-12-01",
      isImportant: true,
      isCompleted: false,
    },
    {
      id: 2,
      title: "Read Book",
      description: "Finish reading 'Atomic Habits'.",
      date: "2023-12-03",
      isImportant: false,
      isCompleted: false,
    },
    {
      id: 3,
      title: "Exercise",
      description: "Go for a 30-minute run in the park.",
      date: "2023-12-05",
      isImportant: false,
      isCompleted: true,
    },
    {
      id: 4,
      title: "Team Meeting",
      description: "Weekly team meet.",
      date: "2023-12-02",
      isImportant: true,
      isCompleted: true,
    },
    {
      id: 5,
      title: "Doctor Appointment",
      description: "Annual health check-up at the clinic.",
      date: "2023-12-06",
      isImportant: false,
      isCompleted: false,
    },
    {
      id: 6,
      title: "Clean the House",
      description: "Vacuum and dust all rooms.",
      date: "2023-12-07",
      isImportant: true,
      isCompleted: false,
    },
    {
      id: 7,
      title: "Plan Vacation",
      description: "Research destinations.",
      date: "2023-12-10",
      isImportant: false,
      isCompleted: false,
    },
    {
      id: 8,
      title: "Send Emails",
      description: "Respond to important emails.",
      date: "2023-12-04",
      isImportant: true,
      isCompleted: true,
    },
    {
      id: 9,
      title: "Grocery Shopping",
      description: "Buy ingredients for the week’s meal prep.",
      date: "2023-12-08",
      isImportant: false,
      isCompleted: false,
    },
    {
      id: 10,
      title: "Workout",
      description: "strength training workout at the gym.",
      date: "2023-12-09",
      isImportant: false,
      isCompleted: true,
    },
  ];
  
  export default tasks;
  